### ISSUE TITLE
Can't find a fp device on Debian 9 testing after using vfs495_debian.sh script

### ISSUE THREAD

**Issue by gabolander** [PetreBoboc/vfs495#4]
Hi there mate Petre,
I have Debian 9 testing and succesfulily run the script vfs495_debian.sh.
Everything is in its correct place, vcsFPServiceDaemon up and running (systemctl status says "Active and running") but all the time I start fprint_demo as root, I keep getting "No devices found".
I have a HP ProBook 430 G4 with Validity Sensors VFS495 Fingerprint Reader (ID 138a:003f).
Some kernel modules missing or to load with modprobe?
Any other suggestions? Tnx in advance
G.

**Comment by PetreBoboc** [comment]
Hello!

Are you using Debian 9 or Debian testing?

I'm not sure, but I think Debian testing has a problem with `libusb-dev` (same issue on Ubuntu 18.04).

Anyway, I'll see what I can do.

**Comment by PetreBoboc** [comment]
So Debian 10...
I'll see what I can do.

**Comment by PetreBoboc** [comment]
@gabolander, I just fixed the autoinstall script. Try to run it again now. It should work.

**Comment by teddy92** [comment]
@PetreBoboc Is the issue fixed for Ubuntu 18.04? I followed all the steps but fprint doesn't detect any devices.

**Comment by PetreBoboc** [comment]
@teddy92,

1: `rm -rf /usr/lib/libssl.so.0.9.8`
2. `rm -rf /usr/lib/libcrypto.so.0.9.8`
3. Do only step 4 from [here](https://github.com/PetreBoboc/vfs495/blob/master/vfs495_ubuntu_18.04.md)
4. Reboot
5. Run `sudo fprint_demo`

**Comment by gabolander** [comment]
@PetreBoboc thank you, I'll try and let you know!

**Comment by teddy92** [comment]
@PetreBoboc Thanks for the suggestion, but sadly still no devices found.

**Comment by teddy92** [comment]
I solved my problem by downloading the suse drivers for my zbook 14 (https://ftp.hp.com/pub/softpaq/sp84501-85000/sp84530.tar), converted the rpm with alien as stated here https://askubuntu.com/questions/385372/vfs-495-finger-print-reader-not-working-in-ubuntu, rebooted and voila it's working!
Thank you so much for this tutorial!
